import test from 'node:test';import assert from 'node:assert/strict';import {validate,position,due,demo,peri} from '../src/core.js';
test('未確認時刻を自動タイムラインに含めない',()=>{assert.equal(position(peri,100).list.length,0);assert.equal(validate(peri).events.length,9)});
test('現在と次を時刻で判定し、入力順が違っても並べる',()=>{const data={...demo,events:[...demo.events].reverse()};assert.equal(position(data,25).list[position(data,25).current].name,'右で頭割り');assert.equal(position(data,25).next.time,40)});
test('音声の予告時刻を跨いだ場合だけ再生対象にする',()=>{assert.equal(due(demo,4,5).length,1);assert.equal(due(demo,5,6).length,0);const zero={...demo,events:[{...demo.events[0],time:0}]};assert.equal(due(zero,-.001,0).length,1)});
test('負数、不明な音声ID、文字列時刻を拒否',()=>{for(const change of [{time:-1},{time:'18'},{voiceParts:['unknown']},{voiceBefore:-1}])assert.throws(()=>validate({...demo,events:[{...demo.events[0],...change}]}))});

test('強調対象は次の行動。発生時刻ちょうどで次へ移る',async()=>{const {upcoming}=await import('../src/core.js');assert.equal(upcoming(demo,0).next.time,10);assert.equal(upcoming(demo,9.9).visible[0].time,10);assert.equal(upcoming(demo,10).visible[0].time,25);assert.equal(upcoming(demo,55).next,undefined);assert.deepEqual(upcoming(demo,55).visible,[]);assert.deepEqual(upcoming(peri,0).visible,[])});
test('音声カテゴリは全パーツを重複なく収録。既存JSONとも互換',async()=>{const {parts,partGroups}=await import('../src/core.js');const ids=partGroups.flatMap(g=>g.ids);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...ids].sort(),Object.keys(parts).sort());assert.doesNotThrow(()=>validate(demo));assert.doesNotThrow(()=>validate({...demo,events:[{...demo.events[0],voiceParts:['north','tower','then','antiknockback']}]}));});

test('3ボスは個別データ、未確認時刻で音声IDは有効。端末の編集を上書きしない',async()=>{const {presets,addPresets}=await import('../src/presets.js');assert.equal(Object.keys(presets).length,4);for(const p of Object.values(presets)){assert.doesNotThrow(()=>validate(p));assert.ok(p.events.every(e=>Number.isFinite(e.time)));assert.match(p.boss,/暫定/);assert.ok(p.events.length>=9)}const edited={version:1,boss:'自作',events:[]};const result=addPresets({'advanced-darya':edited,custom:edited});assert.equal(result['advanced-darya'],edited);assert.equal(result.custom,edited);assert.equal(Object.keys(result).length,6);assert.ok(result['advanced-darya-provisional']);});

 test('未編集の旧プリセットは更新し、編集済み時刻は保持する',async()=>{const {presets,addPresets}=await import('../src/presets.js');const {default:legacy}=await import('../src/data/legacy-darya.json',{with:{type:'json'}});assert.deepEqual(addPresets({'advanced-darya':legacy})['advanced-darya'],presets['advanced-darya']);const changed=structuredClone(legacy);changed.events[0].time=99;const result=addPresets({'advanced-darya':changed});assert.equal(result['advanced-darya'].events[0].time,99);assert.ok(result['advanced-darya-provisional']);assert.deepEqual(addPresets(result),result);});

test('前版の未編集データと退避項目を補正し、編集済み項目は保持する',async()=>{const {presets,addPresets}=await import('../src/presets.js');const {default:previous}=await import('../src/data/previous-pari.json',{with:{type:'json'}});assert.deepEqual(addPresets({'advanced-pari':previous})['advanced-pari'],presets['advanced-pari']);const edited={...previous,boss:'編集済み'};const migrated=addPresets({'advanced-pari':edited,'advanced-pari-provisional':previous});assert.equal(migrated['advanced-pari'],edited);assert.deepEqual(migrated['advanced-pari-provisional'],presets['advanced-pari']);const custom={...previous,boss:'別の編集'};const result=addPresets({'advanced-pari':edited,'advanced-pari-provisional':custom});assert.equal(result['advanced-pari-provisional'],custom);assert.deepEqual(result['advanced-pari-offset10'],presets['advanced-pari']);assert.deepEqual(addPresets(result),result);});

test('極エヌオーは全編を読み込み、新規プリセットを端末編集を保持して追加する',async()=>{const {presets,addPresets}=await import('../src/presets.js');const boss=validate(presets['extreme-enuo']);assert.equal(boss.events.length,42);assert.equal(boss.events[0].time,9);assert.equal(boss.events.at(-1).time,650);assert.equal(boss.events.find(e=>e.name==='ライトレス・ワールド').time,262);assert.ok(boss.events.every((e,i)=>i===0||e.time>=boss.events[i-1].time));const edited={...boss,boss:'個人用エヌオー'};const lib=addPresets({'extreme-enuo':edited});assert.equal(lib['extreme-enuo'],edited);assert.deepEqual(lib['extreme-enuo-provisional'],boss);assert.deepEqual(addPresets(lib),lib);});

test('全体補正は確定時刻だけを書き換え、音声予告・順番を保持する',async()=>{const {shiftTimes}=await import('../src/core.js');const source={...demo,events:[...demo.events,{...demo.events[0],time:null}]};const before=structuredClone(source);const shifted=shiftTimes(source,10);assert.deepEqual(shifted.events.map(e=>e.time),[20,35,50,65,null]);assert.deepEqual(source,before);assert.deepEqual(shiftTimes(shifted,-10),source);assert.deepEqual(shifted.events.map(e=>e.voiceBefore),source.events.map(e=>e.voiceBefore));assert.equal(shiftTimes({...demo,events:[{...demo.events[0],time:.1}]},.2).events[0].time,.3);});
test('補正で範囲を外れる場合は全行を変更せず拒否する',async()=>{const {shiftTimes}=await import('../src/core.js');const before=structuredClone(demo);for(const offset of [-11,86400,NaN,Infinity,'10'])assert.throws(()=>shiftTimes(demo,offset));assert.deepEqual(demo,before);assert.equal(shiftTimes(demo,-10).events[0].time,0);});

test('一括予告設定は経過秒を維持し、コール時刻だけ変える',async()=>{const {setVoiceLead}=await import('../src/core.js');const original=structuredClone(demo);const changed=setVoiceLead(demo,8);assert.deepEqual(changed.events.map(e=>e.time),demo.events.map(e=>e.time));assert.equal(due(changed,1,2)[0].name,'全体攻撃');assert.equal(due(changed,4,5).length,0);assert.equal(due(setVoiceLead(demo,0),9,10)[0].name,'全体攻撃');assert.equal(setVoiceLead(peri,8).events[0].time,null);for(const n of [-1,121,NaN,Infinity,'8'])assert.throws(()=>setVoiceLead(demo,n));assert.deepEqual(demo,original);});

test('日本語コールは強攻撃と頭割りの読みを指定し、表示名は保持する',async()=>{const {parts,speechText}=await import('../src/core.js');assert.equal(speechText('buster'),'きょうこうげき');assert.equal(speechText('stack'),'あたまわり');assert.equal(speechText('pair'),'ペアあたまわり');assert.equal(speechText('right'),'右');assert.equal(parts.buster,'強攻撃');assert.equal(parts.stack,'頭割り');});
