import test from 'node:test';import assert from 'node:assert/strict';import {validate,position,due,demo,peri} from '../src/core.js';
test('未確認時刻を自動タイムラインに含めない',()=>{assert.equal(position(peri,100).list.length,0);assert.equal(validate(peri).events.length,9)});
test('現在と次を時刻で判定し、入力順が違っても並べる',()=>{const data={...demo,events:[...demo.events].reverse()};assert.equal(position(data,25).list[position(data,25).current].name,'右で頭割り');assert.equal(position(data,25).next.time,40)});
test('音声の予告時刻を跨いだ場合だけ再生対象にする',()=>{assert.equal(due(demo,4,5).length,1);assert.equal(due(demo,5,6).length,0);const zero={...demo,events:[{...demo.events[0],time:0}]};assert.equal(due(zero,-.001,0).length,1)});
test('負数、不明な音声ID、文字列時刻を拒否',()=>{for(const change of [{time:-1},{time:'18'},{voiceParts:['unknown']},{voiceBefore:-1}])assert.throws(()=>validate({...demo,events:[{...demo.events[0],...change}]}))});

test('強調対象は次の行動。発生時刻ちょうどで次へ移る',async()=>{const {upcoming}=await import('../src/core.js');assert.equal(upcoming(demo,0).next.time,10);assert.equal(upcoming(demo,9.9).visible[0].time,10);assert.equal(upcoming(demo,10).visible[0].time,25);assert.equal(upcoming(demo,55).next,undefined);assert.deepEqual(upcoming(demo,55).visible,[]);assert.deepEqual(upcoming(peri,0).visible,[])});
test('音声カテゴリは全パーツを重複なく収録。既存JSONとも互換',async()=>{const {parts,partGroups}=await import('../src/core.js');const ids=partGroups.flatMap(g=>g.ids);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...ids].sort(),Object.keys(parts).sort());assert.doesNotThrow(()=>validate(demo));assert.doesNotThrow(()=>validate({...demo,events:[{...demo.events[0],voiceParts:['north','tower','then','antiknockback']}]}));});

test('3ボスは個別データ、未確認時刻で音声IDは有効。端末の編集を上書きしない',async()=>{const {presets,addPresets}=await import('../src/presets.js');assert.equal(Object.keys(presets).length,3);for(const p of Object.values(presets)){assert.doesNotThrow(()=>validate(p));assert.ok(p.events.every(e=>Number.isFinite(e.time)));assert.match(p.boss,/暫定/);assert.ok(p.events.length>=10)}const edited={version:1,boss:'自作',events:[]};const result=addPresets({'advanced-darya':edited,custom:edited});assert.equal(result['advanced-darya'],edited);assert.equal(result.custom,edited);assert.equal(Object.keys(result).length,5);assert.ok(result['advanced-darya-provisional']);});

 test('未編集の旧プリセットは更新し、編集済み時刻は保持する',async()=>{const {presets,addPresets}=await import('../src/presets.js');const {default:legacy}=await import('../src/data/legacy-darya.json',{with:{type:'json'}});assert.deepEqual(addPresets({'advanced-darya':legacy})['advanced-darya'],presets['advanced-darya']);const changed=structuredClone(legacy);changed.events[0].time=99;const result=addPresets({'advanced-darya':changed});assert.equal(result['advanced-darya'].events[0].time,99);assert.ok(result['advanced-darya-provisional']);assert.deepEqual(addPresets(result),result);});
