import {Client,GatewayIntentBits,Events,ChannelType,MessageFlags} from 'discord.js';
import {joinVoiceChannel,entersState,VoiceConnectionStatus,createAudioPlayer,createAudioResource,AudioPlayerStatus,StreamType,NoSubscriberBehavior} from '@discordjs/voice';
import ffmpeg from 'ffmpeg-static';import {spawn} from 'node:child_process';import {config} from './config.js';import {timelines,load,audioFiles} from './files.js';import {Scheduler} from './scheduler.js';import {parts,position,clock} from '../src/core.js';
const cfg=config(),client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates]});
const player=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Pause}});let connection,scheduler,paths={},queue=[],generation=0,worker=false,decoder,cancelPlay;
function cancel(){generation++;queue=[];cancelPlay?.();cancelPlay=null;decoder?.kill();decoder=null;player.stop(true)}
function playFile(file,gen){return new Promise((resolve,reject)=>{if(gen!==generation)return resolve();let finished=false;const done=error=>{if(finished)return;finished=true;clearTimeout(timeout);player.off(AudioPlayerStatus.Idle,idle);player.off('error',bad);child.kill();if(decoder===child)decoder=null;cancelPlay=null;error?reject(error):resolve()};const idle=()=>done(),bad=()=>done(Error('音声の再生に失敗しました。'));const child=decoder=spawn(ffmpeg,['-hide_banner','-loglevel','error','-i',file,'-f','s16le','-ar','48000','-ac','2','pipe:1'],{stdio:['ignore','pipe','ignore']});const timeout=setTimeout(()=>done(Error('音声が長すぎるか再生が停止しました。')),30000);cancelPlay=()=>done();child.on('error',()=>done(Error('FFmpegを起動できません。setup.cmdを再実行してください。')));child.on('exit',code=>{if(code&&gen===generation)done(Error('音声ファイルを読み込めません。'))});player.once(AudioPlayerStatus.Idle,idle);player.once('error',bad);player.play(createAudioResource(child.stdout,{inputType:StreamType.Raw}));})}
function enqueue(ids,files=paths){queue.push({ids,files,gen:generation});drain()}
async function drain(){if(worker)return;worker=true;try{while(queue.length){const job=queue.shift();for(const id of job.ids){if(job.gen!==generation)break;if(!job.files[id])throw Error(`音声がありません: ${parts[id]}`);await playFile(job.files[id],job.gen)}}}catch(e){console.error(e.message);scheduler?.pause();cancel()}finally{worker=false;if(queue.length)drain()}}
async function join(member){const channel=member.voice.channel;if(!channel||channel.type!==ChannelType.GuildVoice)throw Error('通常のボイスチャンネルに参加してから操作してください。');if(connection?.joinConfig.channelId===channel.id&&connection.state.status===VoiceConnectionStatus.Ready)return; scheduler?.pause();cancel();connection?.destroy();connection=joinVoiceChannel({channelId:channel.id,guildId:channel.guild.id,adapterCreator:channel.guild.voiceAdapterCreator,selfDeaf:true});connection.on('error',()=>{scheduler?.pause();console.error('ボイス接続エラー。/joinで接続し直してください。')});connection.on(VoiceConnectionStatus.Disconnected,()=>{scheduler?.pause();console.error('ボイス接続が切れたため停止しました。/joinで再接続してください。')});try{await entersState(connection,VoiceConnectionStatus.Ready,20000);connection.subscribe(player)}catch{connection.destroy();connection=undefined;throw Error('ボイス接続失敗。Botの接続・発言権限とネットワークを確認してください。')}}
let busy=false;
client.on(Events.InteractionCreate,async i=>{
 if(!i.isChatInputCommand()&&!i.isAutocomplete())return;
 const allowed=i.guildId===cfg.DISCORD_GUILD_ID&&i.user.id===cfg.DISCORD_OWNER_ID;
 if(i.isAutocomplete()){try{if(!allowed)return await i.respond([]);const q=i.options.getFocused().toLowerCase();const all=await timelines();await i.respond(all.filter(x=>x.file.toLowerCase().includes(q)||x.data.boss.toLowerCase().includes(q)).slice(0,25).map(x=>({name:`${x.data.boss} (${x.file})`.slice(0,100),value:x.file.slice(0,100)})))}catch{await i.respond([]).catch(()=>{})}return;}
 if(!allowed)return i.reply({content:'このBotは設定した本人が指定サーバー内で操作します。',flags:MessageFlags.Ephemeral});
 if(busy)return i.reply({content:'前の操作を処理しています。少し待ってください。',flags:MessageFlags.Ephemeral});busy=true;
 try{await i.deferReply({flags:MessageFlags.Ephemeral});let response;switch(i.commandName){
 case'list':{const all=await timelines();response=all.length?all.map(x=>`${x.file}：${x.data.boss}`).join('\n').slice(0,1900):'timelinesフォルダにJSONまたはZIPを入れてください。';break;}
 case'join':await join(await i.guild.members.fetch(i.user.id));response='ボイスチャンネルに参加しました。';break;
 case'leave':scheduler?.pause();cancel();connection?.destroy();connection=undefined;response='退出しました。';break;
 case'start':{const file=i.options.getString('boss');if(file){const item=await load(file);if(!position(item.data,0).list.length)throw Error('秒数が未設定です。編集画面で設定してください。');const readyPaths=await audioFiles(item);scheduler?.pause();cancel();paths=readyPaths;scheduler=new Scheduler(item.data,{emit:e=>enqueue(e.voiceParts),cancel});}if(!scheduler)throw Error('/start boss:ファイル名 でタイムラインを選択してください。');await join(await i.guild.members.fetch(i.user.id));scheduler.start();response=`${scheduler.data.boss}：${clock(scheduler.time())}から開始しました。`;break;}
 case'pause':if(!scheduler)throw Error('タイムラインを選択してください。');scheduler.pause();response=`${clock(scheduler.time())}で停止しました。`;break;
 case'reset':scheduler?.reset();cancel();response='0秒へ戻しました。/startで開始します。';break;
 case'seek':if(!scheduler)throw Error('タイムラインを選択してください。');scheduler.seek(i.options.getNumber('seconds',true));response=`${clock(scheduler.time())}へ移動しました。過去の音声は再生しません。`;break;
 case'status':{if(!scheduler){response='タイムライン未選択';break}const t=scheduler.time(),p=position(scheduler.data,t);response=`${scheduler.data.boss} / ${clock(t)} / ${scheduler.running?'進行中':'停止中'}\n${p.next?`次：${p.next.name}（あと${Math.ceil(p.next.time-t)}秒）`:'登録タイムライン終了'}`;break;}
 case'test':await join(await i.guild.members.fetch(i.user.id));if(scheduler?.running)throw Error('タイムライン停止中に試聴してください。');const testPaths=await audioFiles({file:'test.json',audio:{},data:{events:[{voiceParts:['right','stack']}]}});cancel();enqueue(['right','stack'],testPaths);response='「右・頭割り」を再生します。';break;
 default:throw Error('未対応のコマンドです。');}await i.editReply({content:response,allowedMentions:{parse:[]}});
 }catch(e){const text=e.message?.includes('TOKEN')?'認証設定を確認してください。':e.message||'操作に失敗しました。';if(i.deferred)await i.editReply({content:text.slice(0,1900),allowedMentions:{parse:[]}}).catch(()=>{});else await i.reply({content:text,flags:MessageFlags.Ephemeral}).catch(()=>{});}finally{busy=false}
});
client.once(Events.ClientReady,c=>console.log(`起動しました: ${c.user.tag}。Ctrl+Cで終了。`));client.on('error',()=>console.error('Discord接続エラー。'));const interval=setInterval(()=>scheduler?.tick(),100);
function shutdown(){clearInterval(interval);scheduler?.pause();cancel();connection?.destroy();client.destroy();process.exit(0)}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
try{await client.login(cfg.DISCORD_TOKEN)}catch{clearInterval(interval);client.destroy();console.error('ログイン失敗。.envのトークンとネットワークを確認してください。');process.exitCode=1}
