import test from 'node:test';import assert from 'node:assert/strict';import {Scheduler} from './scheduler.js';import {config} from './config.js';import {demo} from '../src/core.js';import {load,audioFiles} from './files.js';
function fixture(){let now=0,events=[],cancels=0;const s=new Scheduler(demo,{clock:()=>now,emit:e=>events.push(e.name),cancel:()=>cancels++});return {s,events,advance:n=>{now+=n*1000;s.tick()},cancels:()=>cancels}}
test('予告を一度だけ実行、停止中は進まない、再開できる',()=>{const f=fixture();f.s.start();for(let i=0;i<5;i++)f.advance(1);assert.deepEqual(f.events,['全体攻撃']);f.advance(.1);assert.equal(f.events.length,1);f.s.pause();const t=f.s.time();f.advance(10);assert.equal(f.s.time(),t);f.s.start();f.advance(1);assert.equal(f.s.time(),t+1)});
test('時間補正は過去の予告を再生しない。リセットで再試行',()=>{const f=fixture();f.s.start();f.s.seek(24);f.advance(1);assert.equal(f.events.length,0);f.s.reset();f.s.start();for(let i=0;i<5;i++)f.advance(1);assert.equal(f.events.length,1);assert.throws(()=>f.s.seek(-1));assert.throws(()=>f.s.seek(NaN))});
test('長時間の処理停止では遅れた音声を読み上げない。終了時刻を保持',()=>{const f=fixture();f.s.start();f.advance(60);assert.equal(f.events.length,0);assert.equal(f.s.running,false);assert.equal(f.s.time(),60)});
test('設定不足と不正IDを拒否、トークンをエラーに含めない',()=>{assert.throws(()=>config({}));assert.throws(()=>config({DISCORD_TOKEN:'secret-value',DISCORD_CLIENT_ID:'invalid'}),e=>!e.message.includes('secret-value'))});
test('JSONサンプルを読み込み、パストラバーサルを拒否、音声不足を通知',async()=>{const item=await load('sample.json');assert.equal(item.data.events.length,4);await assert.rejects(()=>load('../sample.json'));await assert.rejects(()=>audioFiles(item),/音声が不足/)});

test('ZIPの数字入りIDを認識し、未知のパスを無視',async()=>{const {zipSync,strToU8}=await import('fflate');const {writeFile,rm}=await import('node:fs/promises');const {root}=await import('./files.js');const path=await import('node:path');const file=path.join(root,'timelines','test-import.zip');const data={...demo,events:[{...demo.events[0],voiceParts:['h1']}]};try{await writeFile(file,zipSync({'timeline.json':strToU8(JSON.stringify(data)),'audio/h1.wav':new Uint8Array([1,2]),'../escape.txt':strToU8('ignored')}));const item=await load('test-import.zip');assert.equal(item.audio.h1.ext,'wav');assert.equal(Object.keys(item.audio).length,1);}finally{await rm(file,{force:true})}});
