import {addPresets} from './presets.js';
import {parts,partGroups,upcoming,validate,position,due,clock,demo} from './core.js';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
const $=s=>document.querySelector(s),app=$('#app'),editor=location.pathname.endsWith('editor.html');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const say=s=>$('#message').textContent=s;
let db,data,library,selected,audios={},running=false,elapsed=0,anchor=0,last=-.001,voiceGeneration=0,voiceQueue=Promise.resolve(),activeAudio,wake,cancelPart;
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function get(key){return request(db.transaction('state').objectStore('state').get(key))}
async function put(key,value){return new Promise((resolve,reject)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)})}
function stopVoice(){voiceGeneration++;cancelPart?.();cancelPart=null;window.speechSynthesis?.cancel();if(activeAudio){activeAudio.pause();activeAudio.dispatchEvent(new Event('ended'));}}
function speakPart(id,gen){return new Promise(resolve=>{cancelPart=resolve;if(gen!==voiceGeneration)return resolve();if(audios[id]){const url=URL.createObjectURL(audios[id]);const a=activeAudio=new Audio(url);a.volume=Number($('#volume')?.value??.8);const done=()=>{URL.revokeObjectURL(url);if(activeAudio===a)activeAudio=null;resolve()};a.onended=done;a.onerror=()=>{say('音声を再生できませんでした。ファイル形式を確認してください。');done()};a.play().catch(()=>{say('音声の再生がブロックされました。試聴ボタンで確認してください。');done()});}else if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(parts[id]);u.lang='ja-JP';u.rate=1;u.volume=Number($('#volume')?.value??.8);u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u);}else{say('この端末では読み上げを利用できません。音声ファイルを登録してください。');resolve();}})}
function play(ids){const gen=voiceGeneration;voiceQueue=voiceQueue.catch(()=>{}).then(async()=>{for(const id of ids){if(gen!==voiceGeneration)break;await speakPart(id,gen);}})}
function now(){return running?Math.max(0,elapsed+(performance.now()-anchor)/1000):elapsed}
async function wakeScreen(){try{if('wakeLock'in navigator&&document.visibilityState==='visible')wake=await navigator.wakeLock.request('screen')}catch{say('画面の自動ロックは端末の設定で調整してください。')}}
function pause(){elapsed=now();running=false;stopVoice();wake?.release();wake=null;}
function reset(){pause();elapsed=0;last=-.001;update()}
async function save(){data=validate(data);library[selected]=structuredClone(data);await put('library',library);await put('selected',selected);say('このブラウザに保存しました。');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function usageHelp(){return `<details class="card usage-help"><summary>使い方ヘルプ：保存・書き出し・共有・Discordで使う</summary><p><strong>基本の流れ：Webで編集 → 保存 → JSON／ZIPを書き出して保管 → 使う端末やDiscordへ持ち込む。</strong></p><h2>「保存」はこのブラウザ内への保存</h2><p>編集ページの「保存」は、今使っている端末・ブラウザ内に保存します。別のPC・スマホ・ブラウザとは自動同期されません。GitHubやDiscord側のファイルも更新されません。ブラウザのサイトデータを削除すると失われるため、編集後はファイルも書き出して保管してください。</p><h2>JSONと音声付きZIPの違い</h2><ul><li><strong>JSON書出</strong>：行動・秒数・メモ・音声パーツの組み合わせを保存します。音声ファイルは含みません。DiscordではBot側の共通音声を使います。</li><li><strong>音声付きZIP書出</strong>：タイムラインと、そのボスで使う登録済み音声ファイルをまとめます。端末の合成読み上げ音声は書き出されません。未登録パーツはDiscord側でも共通音声が必要です。</li></ul><p>書き出したファイルはブラウザのダウンロード先に保存されます。初期名は「timeline.json」「timeline.zip」なので、ボスごとに名前を変更すると管理しやすくなります。拡張子の .json／.zip は残してください。</p><h2>別の端末で使う・ほかの人に共有する</h2><ol><li>編集ページで保存し、JSONまたは音声付きZIPを書き出します。</li><li>ファイルを保管するか、使う端末・相手へ渡します。</li><li>受け取った側は、このページ上部の「JSON / ZIP読込」でファイルを選びます。ZIPは展開せず読み込みます。</li></ol><p>読み込んだタイムラインは受け取り側のブラウザに保存されます。ZIPの音声は共通音声パーツへ登録され、ほかのボスでも使われます。</p><h2>Discord Botで使う</h2><ol><li>書き出したJSON／ZIPを、Botを動かすPCの「bot/timelines」フォルダ直下へコピーします。ZIPは展開しません。</li><li>Discordで /list を実行し、追加したファイルを確認します。</li><li>/start の boss欄でファイルを選びます。指定すると0秒から開始します。</li></ol><p>ファイル追加だけならBotの再起動・コマンド再登録は不要です。選択中のファイルを更新した場合は、boss欄で指定し直して読み込みます。同じボスをやり直すときは /reset → 戦闘開始時に /start です。</p><p><a href="./discord.html">Discord版の導入と詳細マニュアルへ</a></p></details>`}
function common(){return `<div class="toolbar"><label>タイムライン<select id="boss">${Object.entries(library).map(([k,v])=>`<option value="${esc(k)}" ${k===selected?'selected':''}>${esc(v.boss)}</option>`).join('')}</select></label><label class="file">JSON / ZIP読込<input id="import" type="file" accept=".json,.zip"></label></div>${usageHelp()}`}
function bindCommon(){ $('#boss').onchange=async e=>{pause();if(editor){try{await save()}catch(err){say(err.message);return}}selected=e.target.value;data=structuredClone(library[selected]);elapsed=0;last=-.001;await put('selected',selected);render()};$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>60*1024*1024)throw Error('ファイルは60MB以内にしてください。');let raw,newAudio={};if(file.name.toLowerCase().endsWith('.zip')){const entries=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:f=>f.originalSize<=30*1024*1024&&(f.name==='timeline.json'||/^audio\/[a-z0-9]+\.(mp3|wav|ogg|m4a|webm)$/.test(f.name))});if(!entries['timeline.json'])throw Error('ZIPにtimeline.jsonがありません。');let total=0;for(const bytes of Object.values(entries))total+=bytes.length;if(total>60*1024*1024)throw Error('ZIPの展開後サイズが大きすぎます。');raw=JSON.parse(strFromU8(entries['timeline.json']));for(const [name,bytes]of Object.entries(entries)){const m=name.match(/^audio\/([a-z0-9]+)\.(mp3|wav|ogg|m4a|webm)$/);if(m&&Object.hasOwn(parts,m[1]))newAudio[m[1]]=new Blob([bytes],{type:({mp3:'audio/mpeg',wav:'audio/wav',ogg:'audio/ogg',m4a:'audio/mp4',webm:'audio/webm'})[m[2]]});}}else raw=JSON.parse(await file.text());const imported=validate(raw);pause();selected=crypto.randomUUID();data=imported;audios={...audios,...newAudio};await put('audio',audios);await save();elapsed=0;last=-.001;render();say('読み込みました。音声はこのブラウザの共通パーツに登録されます。');}catch(err){say(`読み込み失敗: ${err.message}`)}};}
function render(){editor?renderEditor():renderPlayer();bindCommon()}
function renderPlayer(){app.innerHTML=`<h1>戦闘タイムライン</h1>${common()}${data.boss.includes("暫定")?'<p class="card provisional" role="note">暫定タイムライン：秒数は未実測です。行動順・間隔を含め実戦でずれる可能性があります。時間補正を使って確認してください。</p>':''}<section class="card"><div id="timer" class="timer">00:00</div><div id="next" class="countdown"></div><div class="toolbar"><button id="start" class="primary">開始</button><button id="pause">一時停止</button><button id="reset">リセット</button></div><div class="toolbar"><button id="minus">−1秒</button><button id="plus">＋1秒</button><label>指定秒へ移動<input id="seek" type="number" min="0" max="86400" value="0"></label><button id="jump">移動</button></div><div class="toolbar"><label class="check"><input id="sound" type="checkbox" checked>音声ON</label><label>音量<input id="volume" type="range" min="0" max="1" step=".05" value=".8"></label><button id="test">音声テスト</button></div><small>開始は手動です。画面を開いたまま使用してください。未登録音声は端末の合成音声で読み上げます。</small></section><section id="timeline"></section>`;
$('#start').onclick=async()=>{if(running)return;if(!position(data,0).list.length)return say('秒数が未設定です。編集ページで時間を登録してください。');anchor=performance.now();running=true;await wakeScreen();update()};$('#pause').onclick=()=>{pause();update()};$('#reset').onclick=reset;$('#test').onclick=()=>{stopVoice();play(['right','stack'])};$('#sound').onchange=()=>{if(!$('#sound').checked)stopVoice()};const seek=n=>{stopVoice();elapsed=Math.min(86400,Math.max(0,n));anchor=performance.now();last=elapsed;update()};$('#minus').onclick=()=>seek(now()-1);$('#plus').onclick=()=>seek(now()+1);$('#jump').onclick=()=>{const n=Number($('#seek').value);if(Number.isFinite(n))seek(n)};update();}
let drawnKey='';
function update(){if(editor)return;const t=now(),p=position(data,t);$('#timer').textContent=clock(t);$('#start').disabled=running;$('#pause').disabled=!running;$('#next').textContent=p.next?`次：${p.next.name} · あと ${Math.max(0,Math.ceil(p.next.time-t))} 秒`:p.list.length?'登録されたタイムラインは終了しました':'秒数未設定：編集ページで登録してください';const key=`${selected}:${p.current}:${data.events.length}`;if(key!==drawnKey||!$('#timeline').children.length){drawnKey=key;const visible=upcoming(data,t).visible;$('#timeline').innerHTML=visible.map(e=>`<article class="card event ${p.next?.index===e.index?'upcoming':''}"><time>${clock(e.time)}</time><div><strong>${p.next?.index===e.index?'▶ 次：':''}${esc(e.name)}</strong><p>${esc(e.note)}</p></div></article>`).join('')+data.events.filter(e=>e.time===null).map(e=>`<article class="card event"><time>未設定</time><div><strong>${esc(e.name)}</strong><p>${esc(e.note)}</p></div></article>`).join('');}if(running){if(document.visibilityState==='visible'&&t-last<3&&$('#sound').checked)for(const e of due(data,last,t))play(e.voiceParts);last=t;}}
function renderEditor(){app.innerHTML=`<h1>タイムライン編集</h1>${common()}<div class="toolbar"><button id="new">新規作成</button><button id="save" class="primary">保存</button><button id="json">JSON書出</button><button id="zip">音声付きZIP書出</button><button id="delete" class="danger">削除</button></div><label>ボス名<input id="name" maxlength="200" value="${esc(data.boss)}"></label><p class="muted">時間は戦闘開始からの経過秒。空欄は未確認として自動進行から除外します。表示・再生は秒数順です。</p><button id="prepend" class="wide">＋ 先頭に行動を追加</button><section id="events"></section><button id="add" class="wide">＋ 末尾に行動を追加</button><details class="card"><summary>共通音声パーツの登録</summary><p class="muted">音声ファイルがないパーツは端末で読み上げます。登録音声はすべてのボスで共有します。</p>${Object.entries(parts).map(([id,label])=>`<div class="audio-row"><strong>${label}</strong><span>${audios[id]?'登録済':'端末読み上げ'}</span><label class="file">音声登録<input type="file" accept="audio/*" data-audio="${id}"></label><button data-listen="${id}">試聴</button><button data-clear="${id}">解除</button></div>`).join('')}</details><section class="card"><h2>指定秒からテスト</h2><div class="toolbar"><input id="previewTime" type="number" min="0" max="86400" value="0" aria-label="テスト開始秒"><button id="preview">保存して表示ページでテスト</button></div></section>`;
$('#name').oninput=e=>data.boss=e.target.value;$('#save').onclick=async()=>{try{await save();render()}catch(e){say(e.message)}};$('#new').onclick=async()=>{try{await save();selected=crypto.randomUUID();data={version:1,boss:'新しいボス',events:[]};await save();render()}catch(e){say(e.message)}};$('#delete').onclick=async()=>{if(!confirm('このタイムラインを端末から削除しますか？'))return;delete library[selected];if(!Object.keys(library).length){library.sample=structuredClone(demo);}selected=Object.keys(library)[0];data=structuredClone(library[selected]);await put('library',library);await put('selected',selected);render()};$('#json').onclick=async()=>{try{await save();download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'timeline.json')}catch(e){say(e.message)}};$('#zip').onclick=async()=>{try{await save();const entries={'timeline.json':strToU8(JSON.stringify(data,null,2))};const used=new Set(data.events.flatMap(e=>e.voiceParts));for(const id of used){const blob=audios[id];if(!blob)continue;const ext=({'audio/mpeg':'mp3','audio/wav':'wav','audio/x-wav':'wav','audio/ogg':'ogg','audio/mp4':'m4a','audio/webm':'webm'})[blob.type];if(!ext)throw Error('ZIP書出の音声はMP3 / WAV / OGG / M4A / WebMを使用してください。');entries[`audio/${id}.${ext}`]=new Uint8Array(await blob.arrayBuffer());}download(new Blob([zipSync(entries,{level:0})],{type:'application/zip'}),'timeline.zip')}catch(e){say(e.message)}};
const addEvent=first=>{const event={time:null,name:'新しい行動',note:'',voiceParts:[],voiceBefore:5};first?data.events.unshift(event):data.events.push(event);renderEvents();const rows=$('#events').children;const row=rows[first?0:rows.length-1];row?.querySelector('[data-field="name"]')?.focus()};$('#prepend').onclick=()=>addEvent(true);$('#add').onclick=()=>addEvent(false);document.querySelectorAll('[data-audio]').forEach(el=>el.onchange=async()=>{try{const f=el.files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('音声は1ファイル10MB以内にしてください。');audios[el.dataset.audio]=f;await put('audio',audios);renderEditor();bindCommon();say('音声を登録しました。')}catch(e){say(e.message)}});document.querySelectorAll('[data-listen]').forEach(el=>el.onclick=()=>{stopVoice();play([el.dataset.listen])});document.querySelectorAll('[data-clear]').forEach(el=>el.onclick=async()=>{stopVoice();delete audios[el.dataset.clear];await put('audio',audios);renderEditor();bindCommon()});$('#preview').onclick=async()=>{try{await save();const t=Number($('#previewTime').value);if(!Number.isFinite(t)||t<0||t>86400)throw Error('テスト秒数を確認してください。');location.href=`./index.html?seek=${t}`}catch(e){say(e.message)}};renderEvents();}
function renderEvents(){ $('#events').innerHTML=data.events.map((e,i)=>`<article class="card" data-index="${i}"><div class="toolbar"><strong>行動 ${i+1}</strong><button data-action="up" ${i===0?'disabled':''}>↑</button><button data-action="down" ${i===data.events.length-1?'disabled':''}>↓</button><button data-action="remove" class="danger">削除</button></div><div class="grid"><label>経過秒（空欄：未確認）<input data-field="time" type="number" min="0" max="86400" step=".1" value="${e.time??''}"></label><label>技名<input data-field="name" maxlength="300" value="${esc(e.name)}"></label></div><label>対処メモ<textarea data-field="note" maxlength="5000">${esc(e.note)}</textarea></label><h3>音声の組み合わせ</h3><div class="selected chips">${e.voiceParts.map((p,j)=>`<button data-part-remove="${j}" title="タップして削除">${j+1}. ${parts[p]} ×</button>`).join('')||'<small>下のパーツをタップして順番に追加</small>'}</div><div class="chips">${partGroups.map(group=>`<details class="part-group"><summary>${group.label}</summary><div class="chips">${group.ids.map(id=>`<button data-part="${id}">＋${parts[id]}</button>`).join('')}</div></details>`).join('')}</div><div class="toolbar"><label>何秒前に再生<input data-field="voiceBefore" type="number" min="0" max="120" value="${e.voiceBefore}"></label><button data-action="listen">組み合わせを試聴</button><button data-action="clear">音声をクリア</button></div></article>`).join('');
$('#events').querySelectorAll('[data-index]').forEach(row=>{const i=Number(row.dataset.index),e=data.events[i];row.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{const f=input.dataset.field;e[f]=f==='time'?(input.value===''?null:Number(input.value)):f==='voiceBefore'?Number(input.value):input.value});row.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{if(e.voiceParts.length>=20)return say('音声パーツは20個までです。');e.voiceParts.push(b.dataset.part);renderEvents()});row.querySelectorAll('[data-part-remove]').forEach(b=>b.onclick=()=>{e.voiceParts.splice(Number(b.dataset.partRemove),1);renderEvents()});row.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{switch(b.dataset.action){case'up':[data.events[i-1],data.events[i]]=[e,data.events[i-1]];break;case'down':[data.events[i+1],data.events[i]]=[e,data.events[i+1]];break;case'remove':data.events.splice(i,1);break;case'clear':e.voiceParts=[];break;case'listen':stopVoice();play(e.voiceParts);return;}renderEvents()})});}
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopVoice();last=now();wake?.release();}else if(running){last=now();wakeScreen();update()}});
window.addEventListener('pagehide',()=>{pause()});window.addEventListener('beforeunload',e=>{if(editor&&JSON.stringify(data)!==JSON.stringify(library[selected])){e.preventDefault();e.returnValue=''}});
try{const open=indexedDB.open('ff14-battle-timeline',1);open.onupgradeneeded=()=>open.result.createObjectStore('state');db=await request(open);library=addPresets(await get('library')||{sample:structuredClone(demo)});await put('library',library);selected=await get('selected');if(!library[selected])selected=Object.keys(library)[0];data=validate(library[selected]);audios=await get('audio')||{};const seek=Number(new URLSearchParams(location.search).get('seek'));if(Number.isFinite(seek)&&seek>=0&&seek<=86400){elapsed=seek;last=seek>0?seek:-.001;}render();setInterval(update,100);}catch(e){app.innerHTML='<h1>起動できませんでした</h1><p>ブラウザのストレージを有効にして再読み込みしてください。</p>';say(e.message)}
